version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: '${CIRCLE_PROJECT_REPONAME}'
          region: AWS_REGION
          tag: '${CIRCLE_BUILD_NUM}'
      - aws-ecs/deploy-service-update:
          requires:
           - aws-ecr/build-and-push-image
          aws-region: AWS_REGION
          family: '${CIRCLE_PROJECT_REPONAME}-service'
          cluster-name: '${CIRCLE_PROJECT_REPONAME}-cluster'
          container-image-name-updates: 'container=${CIRCLE_PROJECT_REPONAME}-service,image-and-tag=${AWS_ECR_ACCOUNT_URL}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}'
          filters:
            branches:
              only:
                - master
